# Remove both autogenerated linker scripts.
# We need to use the SDRAM version.
rm -f STM32F469NIHX_FLASH.ld
rm -f STM32F469NIHX_RAM.ld

# In-Place sort the IOC file. This makes `git diff` clearer.
IOC=$(find *.ioc) && sort $IOC --version-sort --output=$IOC 

# Format generated code to comply with our style.
clang-format --style=file -i -- **/*.c **/*.h