/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.2 */

#ifndef PB_MACFE_TMS_PROTO_PROTO_TMS_PB_H_INCLUDED
#define PB_MACFE_TMS_PROTO_PROTO_TMS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _macfe_tms_proto_SiltoTms { /* translates to class
                                              macfe::tms::proto::SimtoTms */
    pb_callback_t adc_voltages;            /* 6 channel */
} macfe_tms_proto_SiltoTms;

typedef struct _macfe_tms_proto_TmstoSil { /* translates to class
                                              macfe::tms::proto::TmstoSim */
    float fan_pwm;
    bool debug_led_green;
    bool debug_led_red;
    bool debug_led_nucleo;
} macfe_tms_proto_TmstoSil;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define macfe_tms_proto_SiltoTms_init_default \
    {                                         \
        {                                     \
            {NULL}, NULL                      \
        }                                     \
    }
#define macfe_tms_proto_TmstoSil_init_default {0, 0, 0, 0}
#define macfe_tms_proto_SiltoTms_init_zero \
    {                                      \
        {                                  \
            {NULL}, NULL                   \
        }                                  \
    }
#define macfe_tms_proto_TmstoSil_init_zero {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define macfe_tms_proto_SiltoTms_adc_voltages_tag 1
#define macfe_tms_proto_TmstoSil_fan_pwm_tag 1
#define macfe_tms_proto_TmstoSil_debug_led_green_tag 2
#define macfe_tms_proto_TmstoSil_debug_led_red_tag 3
#define macfe_tms_proto_TmstoSil_debug_led_nucleo_tag 4

/* Struct field encoding specification for nanopb */
#define macfe_tms_proto_SiltoTms_FIELDLIST(X, a) \
    X(a, CALLBACK, REPEATED, FLOAT, adc_voltages, 1)
#define macfe_tms_proto_SiltoTms_CALLBACK pb_default_field_callback
#define macfe_tms_proto_SiltoTms_DEFAULT NULL

#define macfe_tms_proto_TmstoSil_FIELDLIST(X, a)     \
    X(a, STATIC, SINGULAR, FLOAT, fan_pwm, 1)        \
    X(a, STATIC, SINGULAR, BOOL, debug_led_green, 2) \
    X(a, STATIC, SINGULAR, BOOL, debug_led_red, 3)   \
    X(a, STATIC, SINGULAR, BOOL, debug_led_nucleo, 4)
#define macfe_tms_proto_TmstoSil_CALLBACK NULL
#define macfe_tms_proto_TmstoSil_DEFAULT NULL

extern const pb_msgdesc_t macfe_tms_proto_SiltoTms_msg;
extern const pb_msgdesc_t macfe_tms_proto_TmstoSil_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define macfe_tms_proto_SiltoTms_fields &macfe_tms_proto_SiltoTms_msg
#define macfe_tms_proto_TmstoSil_fields &macfe_tms_proto_TmstoSil_msg

/* Maximum encoded size of messages (where known) */
/* macfe_tms_proto_SiltoTms_size depends on runtime parameters */
#define MACFE_TMS_PROTO_PROTO_TMS_PB_H_MAX_SIZE macfe_tms_proto_TmstoSil_size
#define macfe_tms_proto_TmstoSil_size 11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
