
# The following targets are appended to the end of the autogenerated Makefile
# from CubeMX.

# Add a recipe for building the sources to objects without linking them.
# This is used by build_cubemx.cmake
objects: $(OBJECTS)


# Add a recipe for printing any Makefile variable to stdout
# This is used by build_cubemx.cmake.
# Example
# $ make LIBS.value
# -lc -lm -lnosys

%.value:
	@echo $($*)
