/// @author Blake Freer
/// @date 2024-02-27

#include <cstdint>

/**
 * @todo In the future, this type will be generated by simulink.
 */
struct SimulinkInput {
    int16_t AMK_ActualVelocity_R;
    int16_t AMK_MagnetizingCurrent_R;
    int16_t AMK_TorqueCurrent_R;
    bool AMK_bDcOn_R;
    bool AMK_bDerating_R;
    bool AMK_bError_R;
    bool AMK_bInverterOn_R;
    bool AMK_bQuitDcOn_R;
    bool AMK_bQuitInverterOn_R;
    bool AMK_bSystemReady_R;
    bool AMK_bWarn_R;
    uint16_t AMK_ErrorInfo_R;
    float AMK_TempIGBT_R;
    float AMK_TempInverter_R;
    float AMK_TempMotor_R;
    int16_t AMK_ActualVelocity_L;
    int16_t AMK_MagnetizingCurrent_L;
    int16_t AMK_TorqueCurrent_L;
    bool AMK_bDcOn_L;
    bool AMK_bDerating_L;
    bool AMK_bError_L;
    bool AMK_bInverterOn_L;
    bool AMK_bQuitDcOn_L;
    bool AMK_bQuitInverterOn_L;
    bool AMK_bSystemReady_L;
    bool AMK_bWarn_L;
    uint16_t AMK_ErrorInfo_L;
    float AMK_TempIGBT_L;
    float AMK_TempInverter_L;
    float AMK_TempMotor_L;
    uint16_t DI_V_SteeringAngle;
    uint16_t DI_V_BrakePedalPos;
    bool DI_b_DriverButton;
    uint16_t DI_V_AccelPedalPos1;
    uint16_t DI_V_AccelPedalPos2;
    bool BM_b_prechrgContactorSts;
    bool BM_b_HVposContactorSts;
    bool BM_b_HVnegContactorSts;
};