name: Build, Test, and Deploy Project

on:
  push:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project to build (i.e. Demo/Blink)'
        required: false
        default: 'Demo/Blink'
      platform:
        description: 'Platform to build for (i.e. cli, stm32f767)'
        required: false
        default: 'cli'

env:
  DEFAULT_PROJECT: Demo/Blink
  DEFAULT_PLATFORM: cli

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set effective project, platform, and sanitize project name
        id: defaults
        run: |
          project_name="${{ github.event.inputs.project || env.DEFAULT_PROJECT }}"
          platform="${{ github.event.inputs.platform || env.DEFAULT_PLATFORM }}"
          sanitized_project_name=$(echo "$project_name" | sed 's/\//-/g')

          echo "Effective project: $project_name"
          echo "Sanitized project name: $sanitized_project_name"
          echo "Effective platform: $platform"

          echo "::set-output name=project::$project_name"
          echo "::set-output name=sanitized_project_name::$sanitized_project_name"
          echo "::set-output name=platform::$platform"

      - name: Build ${{ steps.defaults.outputs.sanitized_project_name }} for ${{ steps.defaults.outputs.platform }}
        run: |
          cd firmware
          make PROJECT=${{ steps.defaults.outputs.sanitized_project_name }} PLATFORM=${{ steps.defaults.outputs.platform }} build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ steps.defaults.outputs.sanitized_project_name }}-${{ steps.defaults.outputs.platform }}
          path: firmware/build/${{ steps.defaults.outputs.sanitized_project_name }}/${{ steps.defaults.outputs.platform }}

#   deploy:
#     runs-on: self-hosted
#     needs: build
#     environment: deploy
#     steps:
#       - name: Upload sanitized project artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           path: firmware/build/${{ steps.defaults.outputs.sanitized_project_name }}-${{ steps.defaults.outputs.platform }}
#           name: build-artifact-${{ steps.defaults.outputs.sanitized_project_name }}-${{ steps.defaults.outputs.platform }}
