name: Build, Test, and Deploy Project

on:
  push:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project to build (i.e. Demo/Blink)'
        default: 'Demo/Blink'
      platform:
        description: 'Platform to build for (i.e. cli, stm32f767)'
        default: 'cli'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ${{ github.event.inputs.project }} for ${{ github.event.inputs.platform }}
        run: |
          cd firmware
          make PROJECT=${{ github.event.inputs.project }} PLATFORM=${{ github.event.inputs.platform }} build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ github.event.inputs.project }}-${{ github.event.inputs.platform }}
          path: firmware/build/${{ github.event.inputs.project }}/${{ github.event.inputs.platform }}

  deploy:
    runs-on: self-hosted
    needs: build
    environment: deploy
    steps:

      - name: Sanitize project name
        id: sanitize
        run: |
          run: echo "::set-output name=project_name::${GITHUB_EVENT_INPUTS_PROJECT//\//-}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: firmware/build/${{ github.event.inputs.project }}/${{ github.event.inputs.platform }}
          name: build-artifact-${{ steps.sanitize.outputs.project_name }}-${{ github.event.inputs.platform }}
