name: Build Projects

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Change directory to firmware
    - name: Change directory to firmware
      run: cd firmware && ls

    # Build DemoProject
    - name: Build DemoProject
      run: make -C firmware PLATFORM=stm32f767 PROJECT=DemoProject
