name: Manual Test Self-Hosted Runner

on:
  workflow_call:
    inputs:
      project:
        description: 'Project to build (i.e. Demo/Blink)'
        required: true
        type: string
      platform:
        description: 'Platform to build for (i.e. cli, stm32f767)'
        required: true
        type: string
      commit:
        description: 'Commit to build (i.e. main, HEAD^)'
        required: true
        type: string

jobs:
  download-artifact:
    runs-on: self-hosted

    steps:
      - name: Prepare artifact name
        id: prepare-artifact-name
        run: |
            project_name="${{ inputs.project }}" 
            project_name="${project_name//\//-}"
            artifact_name="build-${project_name}-${{ inputs.platform }}-${{ inputs.commit }}"
            echo "artifact_name=${artifact_name}" >> $GITHUB_OUTPUT

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
            name: ${{ steps.prepare-artifact-name.outputs.artifact_name }}
