name: Build Project

on:
  workflow_call:
    inputs:
      project:
        description: 'Project to build (i.e. Demo/Blink)'
        required: true
        type: string
      platform:
        description: 'Platform to build for (i.e. cli, stm32f767)'
        required: true
        type: string

jobs:
  build-upload-project:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ${{ inputs.project }} for ${{ inputs.platform }}
        run: |
          cd firmware
          make PROJECT=${{ inputs.project }} PLATFORM=${{ inputs.platform }} build

      - name: Replace slashes in project name
        id: replace-slashes
        run: |
          project_name="${{ inputs.project }}" 
          project_name="${project_name//\//-}"
          echo "project_name=${project_name}" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: firmware/build/${{ inputs.project }}/${{ inputs.platform }}
          name: ${{ steps.replace-slashes.outputs.project_name }}-$(echo ${{ github.sha }} | cut -c1-7)