name: Run Ansible Playbooks on Raspberry Pi

on:
  push:
  workflow_dispatch:

jobs:
  setup-and-run-ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i scripts/hil/inventory.yml scripts/hil/test_setup.yml
