name: Setup SSH Key on Raspberry Pi

on:
  push:
  workflow_dispatch:

jobs:
  setup-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Add SSH key to Raspberry Pi
      env:
        RPI_USER: ${{ secrets.RPI_USER }}
        RPI_PASSWORD: ${{ secrets.RPI_PASSWORD }}
        RPI_IP_ADDRESS: ${{ secrets.RPI_IP_ADDRESS }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      run: |
        sshpass -p "${RPI_PASSWORD}" ssh -o StrictHostKeyChecking=no ${RPI_USER}@${RPI_IP_ADDRESS}"
          mkdir -p ~/.ssh &&
          chmod 700 ~/.ssh &&
          echo '${SSH_PUBLIC_KEY}' >> ~/.ssh/authorized_keys &&
          chmod 600 ~/.ssh/authorized_keys
        "
