name: Test Project Name

on:
  push:

jobs:
  build-project:
    strategy:
      matrix:
        project: ["Demo/Blink", "Demo/Blink"]
        platform: ["cli", "stm32f767"]
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Reusable Workflow
        uses: ./.github/workflows/reusable-build-project.yml
        with:
          project: ${{ matrix.project }}
          platform: ${{ matrix.platform }}
