name: Test Project Name

on:
  push:

jobs:
  setup-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  build-project:
    strategy:
      matrix:
        config:
          - project: "Demo/Blink"
            platform: "cli"
          - project: "Demo/Blink"
            platform: "stm32f767"
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Reusable Workflow
        uses: ./.github/workflows/reusable-build-project.yml
        with:
          project: ${{ matrix.config.project }}
          platform: ${{ matrix.config.platform }}
