name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  setup:
    runs-on: self-hosted
    outputs:
      matrix-all-projects: ${{ steps.all-projects.outputs.matrix }}
      matrix-modified-projects: ${{ steps.modified-projects.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        run: |
          python3 -m venv .venv

      - name: Get all projects
        id: all-projects
        run: |
          source .venv/bin/activate
          python3 scripts/actions/all_projects.py
          echo "matrix=$(cat all_projects.json)" >> $GITHUB_OUTPUT

      - name: Get modified projects
        id: modified-projects
        env:
          BASE_REF: ${{ github.base_ref || 'HEAD^' }}
        run: |
          source .venv/bin/activate
          # if [ "${{ github.event_name }}" == "pull_request" ]; then
          #   echo "BASE_REF=${{ github.base_ref }}"
          #   BASE_REF="${{ github.base_ref }}" # Target branch of the PR
          # else
          #   echo "BASE_REF=HEAD^"
          #   BASE_REF="HEAD^" # Previous commit for push events
          # fi
          BASE_REF="${{ github.base_ref }}" # Directly use the GitHub Actions variable
          BASE_REF="${BASE_REF:-HEAD^}" # Bash fallback if BASE_REF is empty
          python3 scripts/actions/modified_projects.py origin/$BASE_REF

          echo "matrix=$(cat modified_projects.json)" >> $GITHUB_OUTPUT

  # build-all-projects:
  #   needs: setup
  #   strategy:
  #     fail-fast: false
  #     matrix: 
  #       include: ${{ fromJson(needs.setup.outputs.matrix-all-projects) }}
  #   uses: ./.github/workflows/reusable-build-project.yml
  #   with:
  #     project: ${{ matrix.project }}
  #     platform: ${{ matrix.platform }}

  build-modified-projects:
    needs: setup
    strategy:
      fail-fast: false
      matrix: 
        include: ${{ fromJson(needs.setup.outputs.matrix-modified-projects) }}
    uses: ./.github/workflows/reusable-build-project.yml
    with:
      project: ${{ matrix.project }}
      platform: ${{ matrix.platform }}
