name: Test Project Name

on:
  push:

jobs:
  test-string-replacement:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        uses: ./github-actions/reusable-build-project
        with:
          project: Demo/Blink
          platform: cli